name: Document Bicep Module
description: Creates default markdown README.md documentation for the specified module and commits it to the repository.

inputs:
  root-path:
    description: The root path for the modules.
    required: true

  module-name:
    description: "The name of the module. This should include the full relative path below the root-path, not including any leading or trailing '/'. Example: 'subnet' or 'modules/subnet'."
    required: true

  as-pull-request:
    description: Setting this parameter to 'true' will create a pull request instead of committing directly to the default branch.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Write README
      shell: pwsh
      env:
        rootPath: ${{ inputs.root-path }}
        moduleName: ${{ inputs.module-name }}
      run: |
        #* Normalize module path
        $rootPath = $env:rootPath.Trim("/")
        $moduleName = $env:moduleName.ToLower().Trim("/")
        $moduleDir = Join-Path $rootPath $moduleName

        #* Write README
        & "${{ github.action_path }}/src/New-BicepReadme.ps1" -InputPath $moduleDir
        git add $moduleDir/README.md

    - name: Set Git config
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $repoName = gh repo view --json name -q ".name"
        git config --global user.name "$repoName[bot]"
        git config --global user.email "$repoName[bot]@users.noreply.github.com"

    - name: Push changes
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
        moduleName: ${{ matrix.module-name }}
        asPullRequest: ${{ inputs.as-pull-request == 'true' }}
      run: |
        git pull -q # sync with possible changes that may have happened in the between
        if (git diff --name-only --cached) {
          if ([bool]::Parse($env:asPullRequest)) {
            $branchName = "docs/$($env:moduleName)"
            git checkout -b $branchName
            git commit -am "[Automated changes] Generate-Documentation for $($env:moduleName)"
            git push --set-upstream origin $branchName --force

            if (gh pr list --head $branchName) {
              Write-Host "Pull request already created."
            }
            else {
              gh pr create --fill
            }
          }
          else {
            git commit -am "[Automated changes] Generate-Documentation for $($env:moduleName)"
            git push
          }
        }
        else {
          Write-Host "No changes detected."
        }
